version: "3.7"

services:
  database_takeacar:
    image: postgres
    container_name: database_takeacar
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=takeacar
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: takeacar
    ports:
      - 3333:3333
      - 9229:9229 
    volumes:
      - .:/usr/app
    links:
      - database_takeacar
    depends_on: 
      - database_takeacar

volumes:
  pgdata:
    driver: local