openapi: 3.0.0
info: 
  title: TakeACar Documentation
  description: This is an API
  version: 1.0.0

paths:
  /categories:
    post:
      tags: 
        - Category
      summary: Create a category
      description: Create a new category
      security: 
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              example:
                name: Category's name
                description: Category's description
      responses:
        201:
          description: Created
        500:
          description": Category already exists
    get:
      tags:
        - Category
      summary: List all categories
      description: List all categories
      responses:
        200:
          description: Success
          content:
            application/json: 
              schema: 
                type: array
                items: 
                  type: object
                  properties : 
                    name: 
                      type: string
                    description: 
                      type: string
  /categories/import: 
    post:
      tags: 
        - Category
      summary: Upload a new category
      description: Upload a new category
      security: 
        - bearerAuth: []
      requestBody: 
        content:
          multipart/form-data:
            schema: 
              type: object
              properties: 
                file: 
                  type: string
                  format: binary
      responses: 
        201:
          description: Created
  /specifications:
    post:
      tags: 
        - Specifications
      summary: Create a specification
      description: Create a new specification
      security: 
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/definitions/Specification'
      responses: 
        201: 
          description: Created
        500:
          description: Specification already exists
  /sessions:
    post:
      tags: 
        - Session
      summary: Authenticate a user
      description: Authenticate a user
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/definitions/Sessions'
      responses:
        200: 
          description: OK
        400:
          description: Email or password incorrect!
  /users:
    post:
      tags:
        - User
      summary: Create a new user
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                email:
                  type: string
                password:
                  type: string
                driver_license:
                  type: string
      responses:
        201:
          description: Created
  /users/avatar:
    patch:
      tags:
        - User
      summary: Add an avatar
      description: Add an avatar
      security: 
        - bearerAuth: []
      requestBody: 
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file: 
                  type: string
                  format: binary
      responses:
        204:
          description: No Content

definitions: 
  Specification: 
    type: object
    properties:
      name: 
        type: string
      description: 
        type: string
  Sessions:
    type: object
    properties:
      email: 
        type: string
        description: Email
      password:
        type: string
        description: Password

components: 
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT